# Generated by Django 5.0.3 on 2024-03-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='producs',
            field=models.ManyToManyField(related_name='orders', to='shopapp.product'),
        ),
    ]
