# Generated by Django 5.0.3 on 2024-03-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_order_producs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='producs',
            new_name='products',
        ),
    ]
